apiVersion: v2
name: food-order
description: Sistema completo de pedidos de comida — todos los microservicios
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: users
    version: "0.1.0"
    repository: "file://../charts/users"
  - name: catalog
    version: "0.1.0"
    repository: "file://../charts/catalog"
  - name: orders
    version: "0.1.0"
    repository: "file://../charts/orders"
  - name: payments
    version: "0.1.0"
    repository: "file://../charts/payments"
  - name: notifications
    version: "0.1.0"
    repository: "file://../charts/notifications"
  - name: api-gateway
    version: "0.1.0"
    repository: "file://../charts/api-gateway"