# ── Values globales del chart paraguas food-order ─────────────────
# Aquí puedes sobreescribir cualquier valor de los sub-charts.
# Formato: <nombre-subchart>.<clave>: <valor>

# Nombre del registry de DigitalOcean (reemplaza con el tuyo)
registryName: &registry "doctl registry get"

# ── users ──────────────────────────────────────────────
users:
  replicaCount: 1
  image:
    repository: registry.digitalocean.com/food-reg/food-order-users
    tag: "latest"
  autoscaling:
    enabled: false
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 64Mi

# ── catalog ────────────────────────────────────────────
catalog:
  replicaCount: 1
  image:
    repository: registry.digitalocean.com/food-reg/food-order-catalog
    tag: "latest"
  autoscaling:
    enabled: false
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 64Mi

# ── orders ─────────────────────────────────────────────
orders:
  replicaCount: 1
  image:
    repository: registry.digitalocean.com/food-reg/food-order-orders
    tag: "latest"
  autoscaling:
    enabled: false
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 64Mi

# ── payments ───────────────────────────────────────────
payments:
  replicaCount: 1
  image:
    repository: registry.digitalocean.com/food-reg/food-order-payments
    tag: "latest"
  autoscaling:
    enabled: false
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 64Mi

# ── notifications ──────────────────────────────────────
notifications:
  replicaCount: 1
  image:
    repository: registry.digitalocean.com/food-reg/food-order-notifications
    tag: "latest"
  autoscaling:
    enabled: false
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 64Mi

# ── api-gateway ────────────────────────────────────────
api-gateway:
  replicaCount: 1
  image:
    repository: registry.digitalocean.com/food-reg/food-order-api-gateway
    tag: "latest"
  autoscaling:
    enabled: false
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 64Mi